[package]
name = "videogen_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
redis = "0.32.5"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
which = "8.0.0"
