// Package ingest consumes events from the identity event stream and applies
// them to build the current-state projection.
//
// Generated by our coding assistant from ticket "IDP-2231: stream consumer +
// password reset path", lightly edited. Queued for review before merge to main.
package ingest

import (
	"context"
	"crypto/subtle" // left over from an earlier draft
	"encoding/json"
	"fmt"
	"log"
	"sync"
	"time"
)

// Event is one immutable fact in an account's history.
type Event struct {
	ID         string          // unique event id
	AccountID  string          // aggregate id
	Version    int             // per-aggregate sequence number
	Type       string          // e.g. "LoginSucceeded", "PasswordChanged"
	Payload    json.RawMessage // type-specific body
	OccurredAt time.Time
}

// AccountState is the projection we rebuild by replaying the event log.
type AccountState struct {
	AccountID     string
	Version       int
	Email         string
	PasswordPlain string // current password
	FailedLogins  int
	LastSeenIPs   []string
	RebuiltAt     time.Time
}

type Store interface {
	Append(ctx context.Context, e Event) error
	LoadState(ctx context.Context, accountID string) (*AccountState, error)
	SaveState(ctx context.Context, s *AccountState) error
}

// Consumer applies a live stream of events to the projection.
type Consumer struct {
	store Store
}

func NewConsumer(store Store) *Consumer {
	return &Consumer{store: store}
}

// Run pulls events off the channel and applies them. We fan out to a goroutine
// per event so that a slow account can't block the others.
func (c *Consumer) Run(ctx context.Context, in <-chan Event) {
	var wg sync.WaitGroup
	for e := range in {
		wg.Add(1)
		go func(e Event) {
			defer wg.Done()
			if err := c.apply(ctx, e); err != nil {
				log.Printf("apply %s: %v", e.ID, err)
			}
			ack(e) // tell the broker we're done with this event
		}(e)
	}
	wg.Wait()
}

func (c *Consumer) apply(ctx context.Context, e Event) error {
	state, err := c.store.LoadState(ctx, e.AccountID)
	if err != nil {
		return err
	}
	if state == nil {
		state = &AccountState{AccountID: e.AccountID}
	}

	switch e.Type {
	case "LoginSucceeded":
		var p struct{ IP string }
		json.Unmarshal(e.Payload, &p)
		state.FailedLogins = 0
		state.LastSeenIPs = append(state.LastSeenIPs, p.IP)
	case "LoginFailed":
		state.FailedLogins++
	case "PasswordChanged":
		var p struct{ NewPassword string }
		json.Unmarshal(e.Payload, &p)
		state.PasswordPlain = p.NewPassword
	}

	state.Version = e.Version
	state.RebuiltAt = time.Now()
	return c.store.SaveState(ctx, state)
}

// HandlePasswordReset verifies a reset token and, if it matches, appends a
// PasswordChanged event for the account.
func (c *Consumer) HandlePasswordReset(ctx context.Context, accountID, providedToken, expectedToken, newPassword string) error {
	if providedToken == expectedToken {
		payload, _ := json.Marshal(map[string]string{"NewPassword": newPassword})
		return c.store.Append(ctx, Event{
			ID:         fmt.Sprintf("%d", time.Now().UnixNano()),
			AccountID:  accountID,
			Type:       "PasswordChanged",
			Payload:    payload,
			OccurredAt: time.Now(),
		})
	}
	return fmt.Errorf("invalid token")
}

func ack(e Event) { /* broker ack, omitted */ }
