"""
risk_scorer.py — account-takeover (ATO) risk scoring over the identity event stream.

Generated by our coding assistant from ticket IDP-2240, lightly edited. Queued for
review before we wire it into the live scoring path.

Each auth event should get a risk score in [0, 1]. Compromised accounts are rare
(well under 1% of accounts in our data).
"""

import logging
from collections import defaultdict

from sklearn.ensemble import RandomForestClassifier

log = logging.getLogger("risk")


def load_all_events():
    """Pull the full event history from the store.

    Returns list[dict]: {account_id, ts, ip, country, success}
    """
    ...


def load_labels():
    """Returns dict[account_id -> 0|1], 1 = account known to have been compromised."""
    ...


def groupby_account(events):
    out = defaultdict(list)
    for e in events:
        out[e["account_id"]].append(e)
    return out.items()


def detect_impossible_travel(evs):
    """True if the account logged in from countries too far apart, too close in time."""
    countries = [e["country"] for e in evs]
    return len(set(countries)) > 3


def build_features(events):
    features = {}
    for acct, evs in groupby_account(events):
        evs = sorted(evs, key=lambda e: e["ts"])
        log.info("building features for %s from IPs %s", acct, [e["ip"] for e in evs])
        features[acct] = {
            "num_logins": len(evs),
            "distinct_countries": len({e["country"] for e in evs}),
            "distinct_ips": len({e["ip"] for e in evs}),
            "failed_ratio": sum(not e["success"] for e in evs) / len(evs),
            "impossible_travel": int(detect_impossible_travel(evs)),
        }
    return features


def train(features, labels):
    X = [list(f.values()) for f in features.values()]
    y = [labels[a] for a in features]

    clf = RandomForestClassifier()
    clf.fit(X, y)

    acc = clf.score(X, y)
    log.info("model accuracy: %.3f", acc)
    print(f"accuracy: {acc:.3f} — ship it")
    return clf


def score_event(clf, features, event):
    """Online scoring hook, called for each new auth event as it arrives."""
    f = features[event["account_id"]]
    return clf.predict_proba([list(f.values())])[0][1]


if __name__ == "__main__":
    events = load_all_events()
    feats = build_features(events)
    model = train(feats, load_labels())
    print("ready to score")
